language: c
sudo: false
addons:
  apt:
    sources:
      - r-packages-precise
    packages:
      - r-base-dev
      - r-recommended
      - pandoc
  postgresql: "9.4"
env:
  - R_LIBS_USER=~/.R/library
cache:
  directories:
    $R_LIBS_USER
before_script:
  - mkdir -p "$R_LIBS_USER"
  - Rscript -e 'if (length(find.package("devtools", quiet = TRUE)) == 0L) { install.packages("devtools", repos = "http://cran.rstudio.com") }'
  - Rscript -e 'if (!require("roxygen")) devtools::install_github("klutometis/roxygen2")'
  - Rscript -e 'if (!require("testthat") || packageVersion("testthat") < package_version("1.0.2")) devtools::install_github("hadley/testthat")'
  - Rscript -e 'if (!require("testthatsomemore")) devtools::install_github("robertzk/testthatsomemore")'
  - Rscript -e 'if (!require("covr")) devtools::install_github("kirillseva/covr")'
  - Rscript -e 'devtools::install_deps(repos = "http://cran.rstudio.com", dependencies = TRUE)'
script:
  - Rscript -e 'res <- try(devtools::test()); quit(save = "no", status = if (sum(as.data.frame(res)$failed) == 0) { 0 } else { 1 }, runLast = FALSE)'
after_success:
  - Rscript -e 'library(covr);coveralls()'
notifications:
  hipchat:
    rooms:
      secure: C/QSVCJr0J4eLU1IF+yFOc0Az5I2oZC/F61b1Gb3OHm2ZtLTTJY+tTD1xO0PMp+FRdDLkV9PpFWei3C+tPOMVQrzHgpB9YL3RCsHbghzH3C9O7eexQMEON1xh4cI+09F+N6CisIdeQYsUEaePZ2/sOGjo1tcBdwxSjKttGslZlw=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
