language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_github syberia/stagerunner robertzk/mungebits robertzk/testthatsomemore kirillseva/covr"
- "./travis-tool.sh github_package robertzk/testthatsomemore"
- "./travis-tool.sh install_deps"
- "./travis-tool.sh github_package jimhester/covr@e3e137fdf27b6e0dfba2f8d8f25b616b1fb81db9"
- "./travis-tool.sh github_package robertzk/objectdiff"
- "./travis-tool.sh install_r testthat microbenchmark"
- "./travis-tool.sh install_r R6"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
sudo: true
env:
  - global:
      - WARNINGS_ARE_ERRORS=1
          - _R_CHECK_FORCE_SUGGESTS_=0
